version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydatabase
    ports:
      - "5454:5432"
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data


  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - mynetwork


networks:
  mynetwork:

volumes:
  postgres_data:
